app/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  post 'queue_worker', :to => 'welcome#queue_worker', :as => :queue_worker

  mount Sidekiq::Web => '/sidekiq'

  root 'welcome#index'

end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def queue_worker
    TestWorker.perform_async
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<p>
  <%= link_to 'Queue Worker', queue_worker_path, :remote => true, :method => :post %>
</p>

<p>
  <%= link_to 'Sidekiq Web', sidekiq_web_path, :target => '_blank' %>
</p>

<ul class="log"></ul>

app/app/views/welcome/queue_worker.js.erb
$('.log').prepend('<li>Queued <%= Time.now %></li>');